export const strings = {
  appName: "UT Scheduler",
  signIn: {
    title: "Welcome back",
    subtitle: "Sign in to view and manage treatment schedules.",
    tagline: "Precision scheduling for precision care.",
    network: "Radiopharmaceutical Care Network",
    emailLabel: "Email",
    passwordLabel: "Password",
    forgot: "Forgot?",
    submit: "Sign in",
    or: "or",
    sso: "Continue with SSO",
    help: "Trouble signing in? Contact your care coordinator.",
    rolePatient: "Patient",
    roleAdmin: "Admin",
    roleToggleAria: "Account role",
    error: "Invalid email or password",
    networkError:
      "Cannot reach the server. It may be waking up — wait a moment and try again.",
    serverError: "Something went wrong on the server. Please try again.",
    roleMismatch:
      "This account does not match the selected role. Choose the correct role or use a different account.",
    frameHint: "Frame 01 · Sign in",
    modeSignIn: "Sign in",
    modeSignUp: "Create account",
    modeToggleAria: "Authentication mode",
    signUpTitle: "Create your account",
    signUpSubtitle: "Register as a patient to book treatment pathways.",
    fullNameLabel: "Full name",
    signUpSubmit: "Create account",
    signUpSwitch: "Already have an account? Sign in",
    signInSwitch: "New here? Create an account",
    emailTaken: "That email is already registered. Sign in instead.",
    signUpError: "Could not create your account. Please try again.",
  },
  patient: {
    title: "Book a pathway",
    selectPathway: "Select pathway",
    earliestAvailable: "Earliest available",
    confirm: "Confirm booking",
    seeOtherTimes: "See other times",
    blocksPlaced: (blocks: number, rejected: number) =>
      `${blocks} blocks placed · ${rejected} earlier attempt${rejected === 1 ? "" : "s"} rejected`,
    searching: "Searching earliest fit…",
    noFit: "No availability today",
    showNextDay: "Show next available day →",
    chooseDifferent: "Choose a different pathway",
    nextOpening: (label: string) => `Next opening — ${label}`,
    busyChip: (time: string, resource: string) =>
      `${time} — ${resource.charAt(0).toUpperCase()}${resource.slice(1)} busy`,
    selected: "Selected",
    blocksDuration: (blocks: number, duration: string) => `${blocks} blocks · ${duration}`,
    logout: "Sign out",
    noPathwaysYet: "No pathways available yet",
    noPathwaysHint: "An admin needs to create a treatment pathway before you can book.",
    availableTimes: "Available times",
    selectedPlacement: "Selected placement",
    noTimesToday: "No openings on this day",
    dragHint: "Drag the pathway on the grid, or pick a time",
    weekendClosed: "Clinic is closed on weekends — pick a weekday to book.",
    pathwayGone: "That pathway is no longer available. Choose another.",
    slotUnavailable: "That time is unavailable",
    bookedSuccess: (range: string) => `Booked ${range}`,
    loadError: "Couldn’t load the schedule.",
    retry: "Retry",
    wakingUp: "Server may be waking up — hang tight, then retry.",
  },
  confirmModal: {
    title: "Confirm your appointment",
    pathwayLine: (name: string, duration: string) => `${name} · ${duration}`,
    when: "When",
    steps: "Steps",
    back: "Back",
    confirm: "Confirm booking",
    confirming: "Booking…",
    conflict: "That slot was just taken. Try the suggested time below.",
    jumpToSuggestion: (time: string) => `Jump to ${time}`,
    noSuggestion: "No other openings remain on this day — try another date.",
  },
  admin: {
    title: "Schedule",
    pathways: "Pathways",
    newPathway: "+ New pathway",
    activeCount: (n: number) => `${n} active`,
    slotsSelected: (n: number) => `${n} slot${n === 1 ? "" : "s"} selected`,
    markUnavailable: "Mark unavailable",
    markAvailable: "Mark available",
    cancelSelection: "Cancel",
    deletePathway: "Delete pathway",
    deletePathwayConfirm: (name: string) => `Delete “${name}”? This cannot be undone.`,
    noPathwaysSidebar: "No pathways yet — create one to get started.",
    utilizedToday: (n: number) => `${n}% utilized today`,
    export: "Export",
    exportDone: "Schedule CSV downloaded",
    logout: "Sign out",
    dragHint: "Drag across slots to block or unblock",
    blockOccupiedError:
      "Can’t block slots that already have a booking. Cancel the booking first.",
  },
  pathwayBuilder: {
    title: "New pathway",
    nameLabel: "Pathway name",
    namePlaceholder: "Lu-177 standard",
    blocks: "Blocks",
    sequence: "Sequence",
    dragReorder: "Drag to reorder",
    start: "Start",
    save: "Save pathway",
    cancel: "Cancel",
    total: (blocks: number, duration: string) => `${blocks} blocks · ${duration} total`,
    durationMin: (n: number) => `${n} min`,
    durationShort: (n: number) => `${n}m`,
    add: "+ Add",
    emptyLane: "Add blocks to build a pathway",
    closeAria: "Close",
    removeStepAria: "Remove step",
    tooLong: (dayHours: number) =>
      `This pathway is longer than the ${dayHours}-hour clinic day — it can never be scheduled.`,
    short: {
      doctor: "Doc",
      nmt: "NMT",
      gap: "Gap",
      scan: "Scan",
    },
  },
  empty: {
    title: "No availability today",
    body: (pathwayName: string, duration: string) =>
      `${pathwayName} needs ${duration} of continuous coverage — it doesn't fit into today's remaining schedule.`,
    showNext: "Show next available day →",
    chooseDifferent: "Choose a different pathway",
    nextOpening: (label: string) => `Next opening — ${label}`,
  },
  grid: {
    time: "Time",
    doctor: "Doctor",
    nmt: "NMT",
    gap: "Gap",
    scan: "Scan",
    patient: "Patient",
    you: "You",
    unavailable: "Unavailable",
  },
  common: {
    loading: "Loading…",
    error: "Something went wrong",
    admin: "Admin",
    patient: "Patient",
    prevWeek: "Previous week",
    nextWeek: "Next week",
  },
} as const;
